# Generated by Django 2.0.4 on 2018-05-16 20:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import user.models
import user.validator


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180505_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='user',
            name='intro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 50 characters or fewer. Letters, digits and .-_ only.', max_length=40, unique=True, validators=[user.validator.validate_check_blacklist, django.core.validators.RegexValidator(regex='^(?=.{3,50}$)(?![_.])(?!.*[_.]{2})(?=.*[a-z])[a-z0-9._]+(?<![_.])$')], verbose_name='username'),
        ),
    ]
